swagger: "2.0"
info:
  version: "1.0.0"
  title: "gateway"
  description: "gateway api specification"
host: "localhost"
basePath: "/docs/specs"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /gateway:
    get:
      produces:
        - "application/json"
      responses:
        "200":
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Gateway"
definitions:
  Gateway:
    type: "object"
    required:
      - "id"
      - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      tag:
        type: "string"
